"""Build eval/dependency-lock.txt from the packages installed in this venv.

For every installed distribution (pip list): download the exact
name==version wheel for this interpreter/platform with this venv's own pip
(--no-deps --only-binary=:all:), sha256 the wheel file, and VERIFY it is
the artifact that is installed: every file hash listed in the wheel's own
*.dist-info/RECORD must equal the hash recorded for that path in the
installed dist-info RECORD. Any mismatch aborts; nothing is written.

Output is pip's hash-checking requirements format, so it is both
machine-parseable (pip install --require-hashes -r ...) and human-readable.

Usage: .venv/bin/python scripts/build_dependency_lock.py
"""
from __future__ import annotations

import csv
import hashlib
import importlib.metadata as md
import io
import json
import platform
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LOCK = REPO / "eval" / "dependency-lock.txt"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def record_hashes(text: str) -> dict:
    out = {}
    for row in csv.reader(io.StringIO(text)):
        if len(row) >= 2 and row[1]:
            out[row[0]] = row[1]
    return out


def installed_record(dist: md.Distribution) -> dict:
    return record_hashes(dist.read_text("RECORD") or "")


def main() -> int:
    listing = json.loads(subprocess.check_output([sys.executable, "-m", "pip", "list", "--format=json"]))
    entries = []
    with tempfile.TemporaryDirectory() as tmp:
        for item in sorted(listing, key=lambda d: d["name"].lower()):
            name, version = item["name"], item["version"]
            dest = Path(tmp) / name
            dest.mkdir()
            subprocess.check_call(
                [sys.executable, "-m", "pip", "download", f"{name}=={version}", "--no-deps",
                 "--only-binary=:all:", "--dest", str(dest), "--quiet"]
            )
            wheels = list(dest.glob("*.whl"))
            if len(wheels) != 1:
                raise SystemExit(f"{name}: expected exactly one wheel, got {wheels}")
            wheel = wheels[0]
            dist = md.distribution(name)
            inst = installed_record(dist)
            with zipfile.ZipFile(wheel) as zf:
                rec_name = [n for n in zf.namelist() if n.endswith(".dist-info/RECORD")]
                if len(rec_name) != 1:
                    raise SystemExit(f"{name}: wheel has {len(rec_name)} RECORD files")
                whl = record_hashes(zf.read(rec_name[0]).decode("utf-8"))
            checked = relocated = 0
            for path, h in whl.items():
                if ".data/" in path:  # installed to a different location (scripts/headers)
                    relocated += 1
                    continue
                if inst.get(path) != h:
                    raise SystemExit(f"{name}: {path} hash {h} != installed {inst.get(path)}; wheel is not the installed artifact")
                checked += 1
            if checked == 0:
                raise SystemExit(f"{name}: no RECORD entries verified")
            entries.append((name, version, wheel.name, sha256(wheel), checked, relocated))
            print(f"{name}=={version}  {wheel.name}  verified {checked} RECORD hashes ({relocated} relocated .data entries skipped)")

    lines = [
        "# Complete dependency lock for this repo's .venv (direct + transitive), generated by",
        "# scripts/build_dependency_lock.py. Each sha256 is of the exact wheel downloaded for this",
        "# interpreter/platform, verified against the installed dist-info RECORD hashes.",
        f"# python {platform.python_version()} ({platform.python_implementation()}), platform {platform.system()} {platform.machine()}",
        "# Install: python -m pip install --require-hashes --no-deps -r eval/dependency-lock.txt",
        "# Wheel hashes are platform-specific (CPython 3.13, Linux x86_64 manylinux wheels).",
        "",
    ]
    for name, version, wheel, digest, checked, relocated in entries:
        lines.append(f"# wheel: {wheel} (verified {checked} RECORD hashes against installed files; {relocated} .data entries relocated)")
        lines.append(f"{name}=={version} \\")
        lines.append(f"    --hash=sha256:{digest}")
    LOCK.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {LOCK} ({len(entries)} packages), sha256 {sha256(LOCK)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
